using UnityEngine;
using UnityEngine.AI;

   [RequireComponent(typeof(NavMeshAgent))]

public class MoveToClickPoint : MonoBehaviour
{
       NavMeshAgent agent;

    // Start is called before the first frame update
    void Start()
       {
           agent = GetComponent<NavMeshAgent>();
       }

    // Update is called once per frame
    void Update()
       {
           if (Input.GetMouseButton(0))
              {
                  RaycastHit hit;

                  if (Physics.Raycast(Camera.main.ScreenPointToRay(Input.mousePosition), out hit, 100f))
                     {
                         agent.destination = hit.point;
                     }
              }
       }
}
